import type { RegistroDocumento } from "./types";

/**
 * Datos de demostración. Permiten mostrar el dashboard completo en el hackathon
 * sin consumir la API ni requerir credenciales. Representan una muestra realista
 * de la cartera de contratos de una empresa de colocación de crédito, procesada
 * con el enrutado híbrido (Cerebras para texto, Claude visión para escaneados).
 */
export const DATOS_EJEMPLO: RegistroDocumento[] = [
  {
    id: "demo-1",
    nombre_archivo: "pagare_001_maria_gomez.pdf",
    hash_sha256: "a1f3…(demo)",
    modelo: "gpt-oss-120b",
    ruta: "cerebras (texto)",
    reverificado: false,
    procesado_en: "2026-06-04T14:02:11.000Z",
    titular: "María Fernanda Gómez Rincón",
    documento_identidad: "C.C. 52.345.678",
    fecha_contrato: "2024-03-12",
    tipo_documento: "Pagaré con carta de instrucciones",
    autorizacion_tratamiento_datos: "presente",
    autorizacion_centrales_riesgo: "presente",
    comunicacion_previa_reporte: "presente",
    cita_textual:
      "El deudor autoriza de manera expresa e irrevocable a EL ACREEDOR para consultar, reportar y actualizar ante las centrales de riesgo (Datacrédito, TransUnion) su comportamiento crediticio, incluyendo información positiva y negativa, conforme a la Ley 1266 de 2008.",
    pagina: 2,
    fundamento:
      "Cláusula expresa que cubre reporte y consulta, e incluye explícitamente el dato negativo. Cumple Ley 1266/2008.",
    confianza: 0.96,
    prioridad: 2,
    requiere_revision_humana: false,
  },
  {
    id: "demo-2",
    nombre_archivo: "contrato_mutuo_014_jcastro.pdf",
    hash_sha256: "b7c2…(demo)",
    modelo: "claude-sonnet-4-6",
    ruta: "cerebras→claude (reverificado)",
    reverificado: true,
    procesado_en: "2026-06-04T14:02:39.000Z",
    titular: "Jorge Iván Castro Peña",
    documento_identidad: "C.C. 79.112.004",
    fecha_contrato: "2023-11-28",
    tipo_documento: "Contrato de mutuo",
    autorizacion_tratamiento_datos: "presente",
    autorizacion_centrales_riesgo: "ambigua",
    comunicacion_previa_reporte: "ausente",
    cita_textual:
      "El cliente autoriza el tratamiento de sus datos personales para las finalidades propias de la relación comercial.",
    pagina: 4,
    fundamento:
      "Cerebras dudó (confianza baja) y Claude re-verificó: autoriza tratamiento general (Ley 1581) pero NO menciona reportes a centrales de riesgo ni el dato negativo. Insuficiente bajo Ley 1266/2008.",
    confianza: 0.79,
    prioridad: 1,
    requiere_revision_humana: true,
  },
  {
    id: "demo-3",
    nombre_archivo: "escaneo_037_sinocr.pdf",
    hash_sha256: "c9d4…(demo)",
    modelo: "claude-sonnet-4-6",
    ruta: "claude (visión, escaneado)",
    reverificado: false,
    procesado_en: "2026-06-04T14:03:02.000Z",
    titular: "Luz Adriana Mejía Soto",
    documento_identidad: "C.C. 43.998.221",
    fecha_contrato: "2022-07-05",
    tipo_documento: "Pagaré (documento escaneado, sin OCR)",
    autorizacion_tratamiento_datos: "ausente",
    autorizacion_centrales_riesgo: "ausente",
    comunicacion_previa_reporte: "ausente",
    cita_textual: null,
    pagina: null,
    fundamento:
      "Sin capa de texto → leído por visión de Claude. No se encontró cláusula de autorización de datos ni de reporte a centrales de riesgo. Riesgo alto: reportar sin autorización es ilegal.",
    confianza: 0.91,
    prioridad: 0,
    requiere_revision_humana: true,
  },
  {
    id: "demo-4",
    nombre_archivo: "contrato_052_rlopez.pdf",
    hash_sha256: "d2e8…(demo)",
    modelo: "gpt-oss-120b",
    ruta: "cerebras (texto)",
    reverificado: false,
    procesado_en: "2026-06-04T14:03:25.000Z",
    titular: "Ricardo Andrés López Vargas",
    documento_identidad: "C.C. 80.456.123",
    fecha_contrato: "2025-01-19",
    tipo_documento: "Contrato de crédito de consumo",
    autorizacion_tratamiento_datos: "presente",
    autorizacion_centrales_riesgo: "presente",
    comunicacion_previa_reporte: "ambigua",
    cita_textual:
      "Autorizo a la entidad para reportar mi información crediticia, positiva y negativa, a los operadores de información financiera, en los términos de la Ley 1266 de 2008.",
    pagina: 3,
    fundamento: "Autorización completa y expresa para reporte de dato negativo. Cumple normativa.",
    confianza: 0.93,
    prioridad: 2,
    requiere_revision_humana: false,
  },
  {
    id: "demo-5",
    nombre_archivo: "pagare_068_ilegible.pdf",
    hash_sha256: "e5a1…(demo)",
    modelo: "claude-sonnet-4-6",
    ruta: "claude (visión, escaneado)",
    reverificado: false,
    procesado_en: "2026-06-04T14:03:48.000Z",
    titular: "No identificado",
    documento_identidad: null,
    fecha_contrato: null,
    tipo_documento: "Documento ilegible / firma faltante",
    autorizacion_tratamiento_datos: "ambigua",
    autorizacion_centrales_riesgo: "ausente",
    comunicacion_previa_reporte: "ausente",
    cita_textual: null,
    pagina: null,
    fundamento:
      "Calidad de escaneo deficiente; no se identifica al titular ni cláusula de centrales de riesgo. Requiere obtener el original.",
    confianza: 0.58,
    prioridad: 0,
    requiere_revision_humana: true,
  },
  {
    id: "demo-6",
    nombre_archivo: "contrato_089_pmoreno.pdf",
    hash_sha256: "f0b3…(demo)",
    modelo: "gpt-oss-120b",
    ruta: "cerebras (texto)",
    reverificado: false,
    procesado_en: "2026-06-04T14:04:10.000Z",
    titular: "Paula Andrea Moreno Díaz",
    documento_identidad: "C.C. 1.020.345.678",
    fecha_contrato: "2024-09-30",
    tipo_documento: "Contrato de mutuo con garantía",
    autorizacion_tratamiento_datos: "presente",
    autorizacion_centrales_riesgo: "presente",
    comunicacion_previa_reporte: "presente",
    cita_textual:
      "La deudora autoriza expresamente la consulta y el reporte de su comportamiento de pago, incluida la cartera vencida, ante las centrales de información financiera.",
    pagina: 5,
    fundamento: "Cláusula clara que incluye cartera vencida (dato negativo). Cumple Ley 1266/2008.",
    confianza: 0.95,
    prioridad: 2,
    requiere_revision_humana: false,
  },
];
